//! Content, compiled in.
//!
//! Scoot ships as a single binary with no install step, so the committed art
//! and sound are embedded rather than looked up at runtime. The paths reach
//! straight into the canonical locations under `Sources/` — there is no
//! Linux-private copy of any sprite, which is the whole point of the monorepo
//! (PORTS.md §3: platforms share content *by construction*).
//!
//! Decoding is deliberately dumb: nearest-neighbor integer scaling happens at
//! draw time, and nothing here ever resamples.

use std::io::Cursor;

/// Tray atlases, generated by `scripts/gen-linux-tray.py`. One per size a
//  panel might ask for; the host picks, we never rescale.
pub const TRAY_ATLASES: &[(u32, &[u8])] = &[
    (16, include_bytes!("../assets/tray/tray-classic-16.png")),
    (22, include_bytes!("../assets/tray/tray-classic-22.png")),
    (24, include_bytes!("../assets/tray/tray-classic-24.png")),
    (32, include_bytes!("../assets/tray/tray-classic-32.png")),
    (48, include_bytes!("../assets/tray/tray-classic-48.png")),
    (64, include_bytes!("../assets/tray/tray-classic-64.png")),
];

/// The v0.1 buddy: a 4-frame 32x32 dance strip (`buddy-classic.json`).
/// Shared verbatim with the macOS app.
pub const BUDDY_SHEET: &[u8] =
    include_bytes!("../../../Sources/Scoot/Resources/Sprites/buddy-classic.png");
pub const BUDDY_MANIFEST: &str =
    include_str!("../../../Sources/Scoot/Resources/Sprites/buddy-classic.json");

/// The committed two-note chime (PRODUCT.md §3: "a distinctive, warm 2-note
/// sound"), synthesized by `scripts/gen-placeholder-assets.py`.
pub const NUDGE_CHIME: &[u8] =
    include_bytes!("../../../Sources/Scoot/Resources/Sounds/nudge-chime.wav");

/// Frames in every tray atlas: resting, then the 4-beat bounce.
pub const TRAY_FRAME_COUNT: u32 = 5;

/// A decoded RGBA8 image. Rows are top-to-bottom, 4 bytes per pixel.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Image {
    pub width: u32,
    pub height: u32,
    pub rgba: Vec<u8>,
}

impl Image {
    pub fn decode(bytes: &[u8]) -> Option<Self> {
        let decoder = png::Decoder::new(Cursor::new(bytes));
        let mut reader = decoder.read_info().ok()?;
        let mut buf = vec![0u8; reader.output_buffer_size()?];
        let info = reader.next_frame(&mut buf).ok()?;

        // The pipeline writes 8-bit RGBA exclusively (pixellib.write_png ->
        // IHDR colour type 6, depth 8). Anything else means the asset changed
        // shape, which should fail loudly here rather than render garbage.
        if info.color_type != png::ColorType::Rgba || info.bit_depth != png::BitDepth::Eight {
            return None;
        }
        buf.truncate(info.buffer_size());
        Some(Self { width: info.width, height: info.height, rgba: buf })
    }

    /// Cut frame `index` out of a horizontal strip of `count` equal cells.
    pub fn frame(&self, index: u32, count: u32) -> Option<Self> {
        if count == 0 || index >= count || self.width % count != 0 {
            return None;
        }
        let fw = self.width / count;
        let x0 = (index * fw) as usize;
        let mut rgba = Vec::with_capacity((fw * self.height * 4) as usize);
        for y in 0..self.height as usize {
            let row = y * self.width as usize * 4;
            let start = row + x0 * 4;
            rgba.extend_from_slice(&self.rgba[start..start + fw as usize * 4]);
        }
        Some(Self { width: fw, height: self.height, rgba })
    }

    /// Nearest-neighbor integer magnification. The only scaling Scoot has —
    /// DESIGN.md §2 makes this constitutional, so the signature cannot even
    /// express a fractional factor.
    pub fn scaled(&self, factor: u32) -> Self {
        if factor <= 1 {
            return self.clone();
        }
        let (w, h) = (self.width * factor, self.height * factor);
        let mut rgba = vec![0u8; (w * h * 4) as usize];
        for y in 0..h as usize {
            let src_row = (y / factor as usize) * self.width as usize * 4;
            for x in 0..w as usize {
                let src = src_row + (x / factor as usize) * 4;
                let dst = (y * w as usize + x) * 4;
                rgba[dst..dst + 4].copy_from_slice(&self.rgba[src..src + 4]);
            }
        }
        Self { width: w, height: h, rgba }
    }

    /// ARGB32 in network byte order — the pixel format StatusNotifierItem's
    /// `IconPixmap` requires.
    pub fn to_argb32(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(self.rgba.len());
        for px in self.rgba.chunks_exact(4) {
            out.extend_from_slice(&[px[3], px[0], px[1], px[2]]);
        }
        out
    }
}

/// The sprite sheet sidecar (CONTRACTS.md §8.1).
#[derive(Clone, Debug, serde::Deserialize)]
pub struct SpriteManifest {
    #[allow(dead_code)]
    pub name: String,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frame_count: u32,
    pub fps: f64,
}

impl SpriteManifest {
    pub fn parse(text: &str) -> Option<Self> {
        // §8.1: "All fields required, all > 0."
        let raw: serde_json::Value = serde_json::from_str(text).ok()?;
        let m = Self {
            name: raw.get("name")?.as_str()?.to_string(),
            frame_width: raw.get("frameWidth")?.as_u64()? as u32,
            frame_height: raw.get("frameHeight")?.as_u64()? as u32,
            frame_count: raw.get("frameCount")?.as_u64()? as u32,
            fps: raw.get("fps")?.as_f64()?,
        };
        if m.frame_width == 0 || m.frame_height == 0 || m.frame_count == 0 || m.fps <= 0.0 {
            return None;
        }
        Some(m)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_tray_atlas_decodes_at_its_declared_size() {
        for (size, bytes) in TRAY_ATLASES {
            let img = Image::decode(bytes).unwrap_or_else(|| panic!("{size}px atlas"));
            assert_eq!(img.height, *size, "{size}px atlas height");
            assert_eq!(
                img.width,
                size * TRAY_FRAME_COUNT,
                "{size}px atlas should hold {TRAY_FRAME_COUNT} frames"
            );
            // Square frames, and the resting frame must actually have art.
            let f0 = img.frame(0, TRAY_FRAME_COUNT).unwrap();
            assert_eq!((f0.width, f0.height), (*size, *size));
            assert!(
                f0.rgba.chunks_exact(4).any(|p| p[3] != 0),
                "{size}px resting frame is fully transparent"
            );
        }
    }

    #[test]
    fn the_resting_tray_frame_is_coloured_not_a_macos_template() {
        // A black-and-alpha icon would vanish into Ubuntu's dark top bar;
        // this is the assertion that keeps the Linux atlas from regressing to
        // the macOS template treatment.
        let img = Image::decode(TRAY_ATLASES[3].1).unwrap();
        let f0 = img.frame(0, TRAY_FRAME_COUNT).unwrap();
        let coloured = f0
            .rgba
            .chunks_exact(4)
            .any(|p| p[3] != 0 && (p[0] != p[1] || p[1] != p[2]));
        assert!(coloured, "resting frame has no colour");
    }

    #[test]
    fn buddy_sheet_matches_its_manifest() {
        let m = SpriteManifest::parse(BUDDY_MANIFEST).expect("manifest parses");
        let img = Image::decode(BUDDY_SHEET).expect("sheet decodes");
        assert_eq!(img.height, m.frame_height);
        assert_eq!(img.width, m.frame_width * m.frame_count);
        assert!(m.fps > 0.0);
    }

    #[test]
    fn frame_extraction_picks_the_right_cell() {
        // 2x1 strip: left pixel red, right pixel blue.
        let img = Image {
            width: 2,
            height: 1,
            rgba: vec![255, 0, 0, 255, 0, 0, 255, 255],
        };
        assert_eq!(img.frame(0, 2).unwrap().rgba, vec![255, 0, 0, 255]);
        assert_eq!(img.frame(1, 2).unwrap().rgba, vec![0, 0, 255, 255]);
        assert!(img.frame(2, 2).is_none(), "out-of-range frame");
        assert!(img.frame(0, 3).is_none(), "indivisible strip");
    }

    #[test]
    fn scaling_is_nearest_neighbor_and_introduces_no_new_colours() {
        let img = Image {
            width: 2,
            height: 1,
            rgba: vec![255, 0, 0, 255, 0, 0, 255, 255],
        };
        let big = img.scaled(3);
        assert_eq!((big.width, big.height), (6, 3));
        // Every output pixel must be one of the two source colours — an
        // interpolating resize would blend them and fail this.
        for px in big.rgba.chunks_exact(4) {
            assert!(
                px == [255, 0, 0, 255] || px == [0, 0, 255, 255],
                "interpolated pixel {px:?}"
            );
        }
        // And the block structure is exact: first 3 columns red, last 3 blue.
        for y in 0..3 {
            for x in 0..6 {
                let p = &big.rgba[(y * 6 + x) * 4..(y * 6 + x) * 4 + 4];
                let expected: [u8; 4] =
                    if x < 3 { [255, 0, 0, 255] } else { [0, 0, 255, 255] };
                assert_eq!(p, expected, "pixel ({x},{y})");
            }
        }
        assert_eq!(img.scaled(1), img, "scale 1 is identity");
    }

    #[test]
    fn argb32_reorders_channels_for_the_tray() {
        let img = Image { width: 1, height: 1, rgba: vec![0x11, 0x22, 0x33, 0x44] };
        assert_eq!(img.to_argb32(), vec![0x44, 0x11, 0x22, 0x33]);
    }

    #[test]
    fn a_manifest_missing_or_zeroing_a_field_is_rejected() {
        assert!(SpriteManifest::parse(r#"{"name":"x","frameWidth":32}"#).is_none());
        assert!(SpriteManifest::parse(
            r#"{"name":"x","frameWidth":0,"frameHeight":32,"frameCount":4,"fps":10.0}"#
        )
        .is_none());
        assert!(SpriteManifest::parse(
            r#"{"name":"x","frameWidth":32,"frameHeight":32,"frameCount":4,"fps":0}"#
        )
        .is_none());
    }
}
