//! Golden-vector conformance (docs/CONTRACTS.md §10): this crate must
//! reproduce Tests/golden/ — generated by the Swift reference — exactly.

use scoot_core::collection::{parse_collection, CollectionState, RedeemResult, METER_TARGET};
use scoot_core::experiments::{
    assign, fnv1a, semver_compare, ExperimentArm, ExperimentDefinition, ExperimentManifest,
    ManifestError,
};
use scoot_core::movement::{MovementDetector, Verdict};
use scoot_core::rng::{uniform, SplitMix64};
use scoot_core::roll::{first_roll, roll, BuddyCatalog, RarityTier};
use scoot_core::scheduler::{
    reduce, ScheduleConfig, SchedulerEffect, SchedulerEvent, SchedulerState, SuspensionReason,
};
use serde_json::Value;
use std::cmp::Ordering;

fn golden(name: &str) -> Value {
    let path = format!("{}/../Tests/golden/{}", env!("CARGO_MANIFEST_DIR"), name);
    let data = std::fs::read(&path).unwrap_or_else(|_| panic!("missing {path}"));
    serde_json::from_slice(&data).expect("golden file must be valid JSON")
}

fn launch_catalog() -> BuddyCatalog {
    let path = format!(
        "{}/../Sources/ScootCore/Resources/buddy-catalog.json",
        env!("CARGO_MANIFEST_DIR")
    );
    BuddyCatalog::load(&std::fs::read(path).expect("catalog readable")).expect("catalog valid")
}

fn u64_field(value: &Value, key: &str) -> u64 {
    value[key].as_str().expect("u64s travel as strings").parse().expect("decimal u64")
}

#[test]
fn splitmix64_and_bounded_draw_and_fnv1a() {
    let vectors = golden("rng.json");
    for case in vectors["splitmix64"].as_array().unwrap() {
        let mut rng = SplitMix64::new(u64_field(case, "seed"));
        for expected in case["values"].as_array().unwrap() {
            assert_eq!(rng.next().to_string(), expected.as_str().unwrap());
        }
    }
    for case in vectors["boundedDraw"].as_array().unwrap() {
        let mut rng = SplitMix64::new(u64_field(case, "seed"));
        let bound = case["bound"].as_u64().unwrap() as usize;
        for expected in case["values"].as_array().unwrap() {
            assert_eq!(uniform(bound, &mut rng) as u64, expected.as_u64().unwrap());
        }
    }
    for case in vectors["fnv1a"].as_array().unwrap() {
        let input = case["input"].as_str().unwrap();
        assert_eq!(fnv1a(input), u64_field(case, "hash"), "fnv1a({input:?})");
    }
}

#[test]
fn rolls_match_reference() {
    let vectors = golden("rolls.json");
    let catalog = launch_catalog();
    for case in vectors["launchCatalog"].as_array().unwrap() {
        let seed = u64_field(case, "seed");
        let mut rng = SplitMix64::new(seed);
        for expected in case["rolls"].as_array().unwrap() {
            assert_eq!(roll(&catalog, &mut rng).id, expected.as_str().unwrap(), "seed {seed}");
        }
        let mut first_rng = SplitMix64::new(seed);
        for expected in case["firstRolls"].as_array().unwrap() {
            assert_eq!(first_roll(&catalog, &mut first_rng).id, expected.as_str().unwrap());
        }
    }
    // Sparse catalog: constructed directly (deliberately unvalidated — it
    // exercises weight renormalization over absent tiers).
    let sparse: BuddyCatalog = serde_json::from_value(serde_json::json!({
        "version": 1,
        "species": [
            {"id": "c", "displayName": "C", "rarity": "common", "spriteSheet": "c"},
            {"id": "r", "displayName": "R", "rarity": "rare", "spriteSheet": "r"}
        ]
    }))
    .unwrap();
    let case = &vectors["sparseCommonRare"];
    let mut rng = SplitMix64::new(u64_field(case, "seed"));
    for expected in case["rolls"].as_array().unwrap() {
        assert_eq!(roll(&sparse, &mut rng).id, expected.as_str().unwrap());
    }
}

#[test]
fn movement_matches_reference() {
    let vectors = golden("movement.json");
    let config = &vectors["config"];
    for case in vectors["cases"].as_array().unwrap() {
        let mut detector = MovementDetector::new(
            config["window"].as_f64().unwrap(),
            config["awayThreshold"].as_f64().unwrap(),
            config["returnThreshold"].as_f64().unwrap(),
        );
        for step in case["steps"].as_array().unwrap() {
            let verdict = detector.observe(
                step["idle"].as_f64().unwrap(),
                step["elapsed"].as_f64().unwrap(),
            );
            let label = match verdict {
                Verdict::Watching => "watching",
                Verdict::MovementDetected => "movementDetected",
                Verdict::WindowExpired => "windowExpired",
            };
            assert_eq!(label, step["verdict"].as_str().unwrap(),
                       "case {}", case["name"]);
        }
    }
}

fn parse_event(value: &Value) -> SchedulerEvent {
    let reason = |value: &Value| match value["reason"].as_str().unwrap() {
        "screenLocked" => SuspensionReason::ScreenLocked,
        "systemSleep" => SuspensionReason::SystemSleep,
        "displaySleep" => SuspensionReason::DisplaySleep,
        other => panic!("unknown reason {other}"),
    };
    match value["type"].as_str().unwrap() {
        "started" => SchedulerEvent::Started,
        "tick" => SchedulerEvent::Tick,
        "suspended" => SchedulerEvent::Suspended(reason(value)),
        "resumed" => SchedulerEvent::Resumed,
        "userRequestedNudge" => SchedulerEvent::UserRequestedNudge,
        "paused" => SchedulerEvent::Paused { duration: value["for"].as_f64() },
        "unpaused" => SchedulerEvent::Unpaused,
        "intervalChanged" => SchedulerEvent::IntervalChanged,
        "clockChanged" => SchedulerEvent::ClockChanged,
        other => panic!("unknown event {other}"),
    }
}

fn encode_state(state: &SchedulerState) -> Value {
    let secs = |seconds: f64| Value::from(seconds as i64);
    match state {
        SchedulerState::Stopped => serde_json::json!({"case": "stopped"}),
        SchedulerState::Running { next_fire } =>
            serde_json::json!({"case": "running", "nextFire": secs(*next_fire)}),
        SchedulerState::Holding { held_at, absence_before } =>
            serde_json::json!({"case": "holding", "heldAt": secs(*held_at),
                               "absenceBefore": secs(*absence_before)}),
        SchedulerState::Paused { until } => serde_json::json!({
            "case": "paused",
            "until": until.map(|u| Value::from(u as i64)).unwrap_or(Value::Null)}),
        SchedulerState::Suspended { reason, since, previous_next_fire } => {
            let reason = match reason {
                SuspensionReason::ScreenLocked => "screenLocked",
                SuspensionReason::SystemSleep => "systemSleep",
                SuspensionReason::DisplaySleep => "displaySleep",
            };
            serde_json::json!({
                "case": "suspended", "reason": reason, "since": secs(*since),
                "previousNextFire": previous_next_fire.map(|p| Value::from(p as i64))
                    .unwrap_or(Value::Null)})
        }
    }
}

fn encode_effect(effect: &SchedulerEffect) -> Value {
    match effect {
        SchedulerEffect::FireNudge => serde_json::json!({"type": "fireNudge"}),
        SchedulerEffect::Log { name, detail } =>
            serde_json::json!({"type": "log", "name": name, "detail": detail}),
    }
}

#[test]
fn scheduler_matches_reference() {
    let vectors = golden("scheduler.json");
    let config_value = &vectors["config"];
    let config = ScheduleConfig {
        interval: config_value["interval"].as_f64().unwrap(),
        idle_grace: config_value["idleGrace"].as_f64().unwrap(),
        reset_threshold: config_value["resetThreshold"].as_f64().unwrap(),
        wake_grace: config_value["wakeGrace"].as_f64().unwrap(),
    };
    for case in vectors["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let mut state = SchedulerState::Stopped;
        for step in case["steps"].as_array().unwrap() {
            let (next, effects) = reduce(
                state,
                parse_event(&step["event"]),
                step["at"].as_f64().unwrap(),
                step["idle"].as_f64().unwrap(),
                &config,
            );
            state = next;
            assert_eq!(encode_state(&state), step["expectState"], "scenario {name}");
            let effects: Vec<Value> = effects.iter().map(encode_effect).collect();
            assert_eq!(Value::from(effects), step["expectEffects"], "scenario {name}");
        }
    }
}

#[test]
fn assignment_matches_reference() {
    let vectors = golden("assignment.json");
    for case in vectors["cases"].as_array().unwrap() {
        let arms = case["arms"].as_array().unwrap().iter()
            .map(|arm| ExperimentArm {
                id: arm["id"].as_str().unwrap().to_string(),
                weight: arm["weight"].as_i64().unwrap(),
            })
            .collect();
        let definition = ExperimentDefinition {
            key: case["key"].as_str().unwrap().to_string(),
            hypothesis: String::new(),
            arms,
        };
        assert_eq!(
            assign(case["installID"].as_str().unwrap(), &definition),
            case["arm"].as_str().unwrap()
        );
    }
}

#[test]
fn semver_matches_reference() {
    let vectors = golden("semver.json");
    for case in vectors["cases"].as_array().unwrap() {
        let result = match semver_compare(case["a"].as_str().unwrap(),
                                          case["b"].as_str().unwrap()) {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        };
        assert_eq!(result, case["result"].as_i64().unwrap(),
                   "compare({}, {})", case["a"], case["b"]);
    }
}

#[test]
fn manifest_matches_reference() {
    let vectors = golden("manifest.json");
    for case in vectors["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let document = case["document"].as_str().unwrap();
        match ExperimentManifest::load(document.as_bytes()) {
            Ok(manifest) => {
                assert!(case["valid"].as_bool().unwrap(), "{name} should be invalid");
                for (version, expected) in case["applicable"].as_object().unwrap() {
                    let keys: Vec<Value> = manifest.applicable(version)
                        .iter().map(|d| Value::from(d.key.clone())).collect();
                    assert_eq!(Value::from(keys), *expected, "{name}@{version}");
                }
            }
            Err(error) => {
                assert!(!case["valid"].as_bool().unwrap(), "{name} should be valid");
                let label = match error {
                    ManifestError::DuplicateKey(_) => "duplicateKey",
                    ManifestError::NoArms(_) => "noArms",
                    ManifestError::NonPositiveWeight(_) => "nonPositiveWeight",
                    ManifestError::InvalidVersion => "invalidVersion",
                    ManifestError::Decode => "decode",
                };
                assert_eq!(label, case["error"].as_str().unwrap(), "{name}");
            }
        }
    }
}

#[test]
fn collection_matches_reference() {
    let vectors = golden("collection.json");
    assert_eq!(METER_TARGET, vectors["meterTarget"].as_i64().unwrap());
    for (tier, expected) in vectors["duplicateSparks"].as_object().unwrap() {
        let tier = match tier.as_str() {
            "common" => RarityTier::Common,
            "uncommon" => RarityTier::Uncommon,
            "rare" => RarityTier::Rare,
            "epic" => RarityTier::Epic,
            "secret" => RarityTier::Secret,
            other => panic!("unknown tier {other}"),
        };
        assert_eq!(tier.duplicate_sparks(), expected.as_i64().unwrap());
    }

    let catalog = launch_catalog();
    let obtained_at = "2026-06-01T12:00:00Z";
    let mut state = CollectionState::default();
    let scenario = &vectors["scenario"];
    for op in scenario["ops"].as_array().unwrap() {
        match op["op"].as_str().unwrap() {
            "credit" => {
                let credit = state.credit_scoot(op["day"].as_str().unwrap());
                assert_eq!(credit.ticket_minted, op["ticketMinted"].as_bool().unwrap());
                assert_eq!(credit.scoots_today, op["scootsToday"].as_i64().unwrap());
                assert_eq!(credit.meter_scoots, op["meterScoots"].as_i64().unwrap());
            }
            "redeem" => {
                let species = catalog.by_id(op["species"].as_str().unwrap()).unwrap();
                let outcome = state.redeem(species, op["givenName"].as_str().unwrap(),
                                           obtained_at);
                let encoded = match outcome {
                    RedeemResult::NoTicket => serde_json::json!({"result": "noTicket"}),
                    RedeemResult::NewBuddy { index } =>
                        serde_json::json!({"result": "newBuddy", "index": index}),
                    RedeemResult::Duplicate { sparks_earned } =>
                        serde_json::json!({"result": "duplicate",
                                           "sparksEarned": sparks_earned}),
                };
                assert_eq!(encoded, op["outcome"]);
            }
            other => panic!("unknown op {other}"),
        }
    }
    // Trailing renames from the reference scenario (CONTRACTS.md §8.3).
    state.rename(0, "  Toast  ");
    state.rename(0, "   ");
    assert_eq!(serde_json::to_value(&state).unwrap(), scenario["finalState"]);

    // v1 -> v2 migration.
    let migration = &vectors["migrationV1"];
    let migrated = parse_collection(migration["v1Document"].as_str().unwrap().as_bytes())
        .expect("v1 migrates");
    let expected = &migration["expected"];
    assert_eq!(migrated.schema_version, expected["schemaVersion"].as_i64().unwrap());
    assert_eq!(migrated.sparks, expected["sparks"].as_i64().unwrap());
    assert_eq!(migrated.roll_tickets, expected["rollTickets"].as_i64().unwrap());
    assert_eq!(migrated.meter_scoots, expected["meterScoots"].as_i64().unwrap());
    assert_eq!(migrated.total_scoots, expected["totalScoots"].as_i64().unwrap());
    assert_eq!(migrated.scoots_today, expected["scootsToday"].as_i64().unwrap());
    assert_eq!(migrated.scoots_day, None);
    let owned_expected = expected["owned"].as_array().unwrap();
    assert_eq!(migrated.owned.len(), owned_expected.len());
    for (owned, expected) in migrated.owned.iter().zip(owned_expected) {
        assert_eq!(owned.species_id, expected["speciesID"].as_str().unwrap());
        assert_eq!(owned.given_name, expected["givenName"].as_str().unwrap());
        assert_eq!(owned.bond_scoots, expected["bondScoots"].as_i64().unwrap());
    }
}
